#!/usr/bin/env python3
"""Roll the PERFORMANCE-LOG into transfer scores per creator + per hook family.

Reads ../PERFORMANCE-LOG.md, ignores header / separator / EXAMPLE / blank rows,
and ranks creators and hook families by measured retention on Alex's account.
Writes ../perf/TRANSFER-SCORES.md. No third-party deps.

Usage: python3 perf/compute_transfer_scores.py
"""
import os, re, statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
LOG = os.path.join(HERE, "..", "PERFORMANCE-LOG.md")
OUT = os.path.join(HERE, "TRANSFER-SCORES.md")

COLS = ["reel", "date", "creator_dna", "hook_family", "keyword", "topic",
        "pred", "s3_hold_pct", "avg_watch_s", "saves", "comments", "notes"]


def num(x):
    try:
        return float(str(x).replace("%", "").strip())
    except (ValueError, AttributeError):
        return None


def parse_rows(path):
    rows = []
    for line in open(path, encoding="utf-8"):
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != len(COLS):
            continue
        if cells[0] in ("reel", "") or set(cells[0]) <= set("-: "):
            continue                      # header / separator / blank
        if cells[0].upper().startswith("EXAMPLE"):
            continue                      # example rows are ignored
        rows.append(dict(zip(COLS, cells)))
    return rows


def group(rows, key):
    """{key_value: {'hold':[...], 'watch':[...], 'n':int}}"""
    out = {}
    for r in rows:
        k = r[key] or "-"
        if k == "-":
            continue
        g = out.setdefault(k, {"hold": [], "watch": [], "n": 0})
        g["n"] += 1
        h, w = num(r["s3_hold_pct"]), num(r["avg_watch_s"])
        if h is not None:
            g["hold"].append(h)
        if w is not None:
            g["watch"].append(w)
    return out


def table(title, grouped):
    lines = [f"### {title}", "",
             "| " + title.split()[0] + " | n | avg 3s-hold % | avg watch (s) |",
             "|---|---|---|---|"]
    def sortkey(kv):
        w = kv[1]["watch"]
        return st.mean(w) if w else -1
    for k, g in sorted(grouped.items(), key=sortkey, reverse=True):
        hold = f"{st.mean(g['hold']):.1f}" if g["hold"] else "-"
        watch = f"{st.mean(g['watch']):.1f}" if g["watch"] else "-"
        lines.append(f"| {k} | {g['n']} | {hold} | {watch} |")
    return "\n".join(lines)


def main():
    rows = parse_rows(LOG)
    real = [r for r in rows if num(r["s3_hold_pct"]) is not None or num(r["avg_watch_s"]) is not None]
    header = ["# TRANSFER SCORES (measured, auto-generated)",
              "> Generated by perf/compute_transfer_scores.py from PERFORMANCE-LOG.md. "
              "Higher = this style/shape keeps Alex's audience watching. Trust a row once n>=3.",
              ""]
    if not real:
        header.append("**No real data yet** — log some shipped reels with retention numbers in "
                      "PERFORMANCE-LOG.md, then re-run. Ranking needs at least a few rows.")
        open(OUT, "w", encoding="utf-8").write("\n".join(header) + "\n")
        print("No real rows yet. Wrote placeholder TRANSFER-SCORES.md.")
        return
    by_creator = group(real, "creator_dna")
    by_family = group(real, "hook_family")
    body = [table("Creator transfer (measured)", by_creator), "",
            table("Hook-family transfer (measured)", by_family), "",
            f"_Based on {len(real)} logged reels with retention data._"]
    # a one-line router recommendation if any creator has n>=3
    ranked = [(k, st.mean(g["watch"])) for k, g in by_creator.items() if g["watch"] and g["n"] >= 3]
    if ranked:
        best = max(ranked, key=lambda x: x[1])
        body.append(f"\n**Router signal:** `{best[0]}` has the best measured avg-watch "
                    f"({best[1]:.1f}s, n>=3) — prefer it when a topic fits two creators.")
    open(OUT, "w", encoding="utf-8").write("\n".join(header + body) + "\n")
    print(f"Wrote TRANSFER-SCORES.md from {len(real)} real rows "
          f"({len(by_creator)} creators, {len(by_family)} families).")


if __name__ == "__main__":
    main()
