import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import path from 'node:path';
// Original short, damped major-sixth resolution. No downloaded music or voices.
const folder=path.join(process.cwd(),'work/higgsfield-replacement/public/v9'),rate=48000,seconds=1.5,n=rate*seconds,pcm=Buffer.alloc(n*4);
for(let i=0;i<n;i++){
 const t=i/rate;let v=0;
 for(const [j,freq] of [261.6256,329.6276,391.9954,440].entries()){
  const age=t-j*.073;if(age<0)continue;
  const env=(1-Math.exp(-age*140))*Math.exp(-age*4.8)*Math.min(1,(seconds-t)/.15);
  v+=env*(Math.sin(2*Math.PI*freq*age)+.15*Math.sin(2*Math.PI*freq*2*age))*.085;
 }
 for(let ch=0;ch<2;ch++)pcm.writeInt16LE(Math.round(Math.max(-1,Math.min(1,v)) *32767),i*4+ch*2);
}
const h=Buffer.alloc(44);h.write('RIFF');h.writeUInt32LE(36+pcm.length,4);h.write('WAVEfmt ',8);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(2,22);h.writeUInt32LE(rate,24);h.writeUInt32LE(rate*4,28);h.writeUInt16LE(4,32);h.writeUInt16LE(16,34);h.write('data',36);h.writeUInt32LE(pcm.length,40);
const file=path.join(folder,'celebrate-v12.wav');writeFileSync(file,Buffer.concat([h,pcm]));
writeFileSync(path.join(folder,'celebrate-v12-ledger.json'),JSON.stringify({file:'celebrate-v12.wav',provenance:'Original deterministic additive synthesis; generated by build-sfx-v12.mjs; no third-party recording',duration:seconds,sampleRate:rate,sha256:createHash('sha256').update(readFileSync(file)).digest('hex'),mixGain:.16,use:'Single crown landing after creator identifies the right-hand Claude result'},null,2)+'\n');
console.log(file);
