import assert from 'node:assert/strict';
import {readFileSync,readdirSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement'),src=path.join(repo,'video/src/youtube');
const require=createRequire(path.join(repo,'video/package.json')),{transformSync}=require('esbuild'),read=n=>readFileSync(path.join(src,n),'utf8');
const evaluate=(code,scope={})=>{const box={module:{exports:{}},...scope};runInNewContext(transformSync(code,{loader:'ts',format:'cjs'}).code,box);return box.module.exports;};
const m=JSON.parse(readFileSync(path.join(project,'roughcut.props.json'))).manifest,old=JSON.parse(readFileSync(path.join(project,'roughcut-v12-baseline.props.json'))).manifest;
assert.deepEqual(m,old,'V13 is a picture/SFX revision: preserve the entire V12 EDL and camera clocks');
const timing=evaluate(read('roughcut-timing.ts')),rows=timing.roughTimeline(m),before=timing.roughTimeline(old),get=id=>rows.find(r=>r.id===id);
assert.deepEqual(m.cameras,old.cameras);assert.deepEqual(m.obs,old.obs);assert.equal(rows.length,47);assert.equal(timing.roughChapters(m).length,6);
for(const r of rows){const b=before.find(b=>b.id===r.id);assert.ok(r.duration>0);if(!['s035','s036','s037'].includes(r.id)){assert.equal(r.start,b.start);assert.equal(r.end,b.end);}if(r.cameraSource){assert.equal(r.cameraPlateSource,b.cameraPlateSource);assert.ok(Math.abs((r.cameraPlateStart-b.cameraPlateStart)/m.fps-(r.start-b.start))<1/m.fps);assert.ok(r.duration<=r.cameraPlateDuration+1);assert.ok(existsSync(path.join(base,'work/higgsfield-replacement/public',r.cameraPlateSource)));}}
assert.equal(get('s035').end,1897.94);assert.equal(get('s036').end,2002.96);assert.equal(get('s037').start,2017.2);assert.equal(get('r-veo-playthrough').end,1870.82);assert.equal(get('s045').end,2459.03);
for(const id of ['s016','s017'])assert.equal(get(id).screenRedaction,'credentials');
const polish=read('YouTubeV9.tsx'),cues=evaluate(polish.slice(polish.indexOf('export const v9Cues:'),polish.indexOf('export const chapterTitles'))).v9Cues;
const fullScenes=evaluate(polish.slice(polish.indexOf('export const fullScenes='),polish.indexOf('const Definition:')),{roughTimeline:timing.roughTimeline}).fullScenes;
const beats=read('ScenesV13.tsx').match(/export const roadmapBeatsV13=\[([^\]]+)\]/)[1].split(',').map(Number);
const soundEvents=evaluate(polish.slice(polish.indexOf('export const soundEvents='),polish.indexOf('export const YouTubeSound:')),{roughTimeline:timing.roughTimeline,roughChapters:timing.roughChapters,fullScenes,v9Cues:cues,roadmapBeatsV13:beats}).soundEvents(m);
for(const hit of soundEvents){assert.ok(hit.at>=0&&hit.at<13713);assert.ok(hit.gain>0&&hit.gain<=(hit.name==='roadmap-ding'?.55:.16));assert.ok(hit.duration>0);assert.ok(existsSync(path.join(base,'work/higgsfield-replacement/public',hit.name==='roadmap-ding'?'v3/glass.wav':'v4/'+hit.name+'.wav')));}
for(const phase of beats)assert.ok(soundEvents.some(hit=>hit.at===Math.round((get('s006').from/30+phase*get('s006').duration/30)*30)&&['latch','roadmap-ding'].includes(hit.name)));
assert.ok(soundEvents.some(hit=>hit.at===Math.round((get('s033').from/30+12.93)*30)&&hit.name==='click'));
for(const c of cues)assert.ok(get(c.id).duration>c.offset*m.fps);
assert.ok(cues.some(c=>c.id==='s033'&&c.title==='Generated with Veo'));
assert.ok(cues.some(c=>c.id==='s034'&&c.feature==='hair'));assert.ok(cues.some(c=>c.id==='s035'&&c.feature==='fabric'));
assert.match(read('StoryScenesV10.tsx'),/data-choice-number=\{i\+1\}/);assert.doesNotMatch(read('StoryScenesV10.tsx'),/RIGHT ·|LEFT ·/);assert.match(read('ScenesV9.tsx'),/OutroV9=(InstallFinaleV12|OutroV19|OutroV22)/);
assert.ok(!cues.some(c=>c.id==='s016'&&c.kind==='definition'),'Only one credential teaching surface');
assert.match(polish,/CredentialSequence=CredentialV13/);assert.match(polish,/<RevealCountdownV13/);assert.match(polish,/<PlaybackStartV13/);assert.match(polish,/<FaceTimerV13/);
assert.match(read('ScenesV9.tsx'),/FeatureVault=(FeatureGateV13|FeatureGateV17|VaultV20)/);assert.match(read('ScenesV9.tsx'),/GuideV9=(FollowAlongV13|GuideV15|GuideV20|GuideV22)/);assert.match(read('ScenesV9.tsx'),/RoadmapV9=(RoadmapV13|RoadmapV15|RoadmapV16|RoadmapV18|RoadmapV19|RoadmapV20)/);
assert.match(read('ScenesV13.tsx'),/data-stable-format-label/);assert.match(read('ScenesV13.tsx'),/FREE setup · description below/);assert.match(read('ScenesV12.tsx'),/FREE setup · description below/);
assert.doesNotMatch(read('typing-focus.ts'),/s023:/);assert.doesNotMatch(read('RoughCut.tsx').split('const Screen:')[0],/s023:/);
assert.match(read('StoryScenesV10.tsx'),/Seedance 2.5/);assert.match(read('StoryScenesV10.tsx'),/strokeDashoffset=\{i===2\?1-choose:1\}/);
for(const name of ['codex.svg','cursor.svg'])assert.ok(existsSync(path.join(base,'work/higgsfield-replacement/public/v3',name)));
assert.match(read('ScenesV12.tsx'),/FREE BONUS/);assert.match(read('ScenesV12.tsx'),/data-synchronized-detail/);assert.match(read('ScenesV12.tsx'),/data-winner="claude-right"/);
assert.match(polish,/find\('s029'\).from-3\*fps/);assert.match(polish,/find\('s043'\).from-3\*fps/);assert.match(polish,/find\('s043'\).from\+108/);
assert.match(read('RoughCut.tsx'),/data-audio-role="obs-narration" src=\{staticFile\(m.obs.source\)\}/);
assert.match(read('RoughCut.tsx'),/data-privacy-mask/);assert.match(read('YouTubeV8Primitives.tsx'),/symmetric-eyes/);
for(const n of ['RoughCut.tsx','StoryScenesV10.tsx','ScenesV12.tsx','ScenesV13.tsx'])for(const tag of read(n).match(/<OffthreadVideo[\s\S]*?\/>/g)||[])assert.match(tag,/\bmuted\b/);
for(const file of readdirSync(src).filter(n=>/\.tsx?$/.test(n)))transformSync(read(file),{loader:file.endsWith('tsx')?'tsx':'ts'});
assert.doesNotMatch(read('ScenesV12.tsx'),/Math.random|Date.now|setTimeout/);
assert.doesNotMatch(read('ScenesV13.tsx'),/Math.random|Date.now|setTimeout/);
console.log('PASS V13: unchanged V12 EDL/camera clocks, privacy, OBS-only narration, single credential surface, stable format text, circular identities/center reveal, face timer, Seedance selection, free setup, muted media and TS/TSX parsing.');
