import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),video=path.join(repo,'video');
const project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement'),work=path.join(base,'work/higgsfield-replacement'),src=path.join(video,'src/youtube');
const require=createRequire(path.join(video,'package.json')),{transformSync}=require('esbuild');
const read=n=>readFileSync(path.join(src,n),'utf8');
const evaluate=(code,scope={})=>{const box={module:{exports:{}},...scope};runInNewContext(transformSync(code,{loader:'ts',format:'cjs'}).code,box);return box.module.exports;};
const m=JSON.parse(readFileSync(path.join(project,'roughcut.props.json'))).manifest;
const old=JSON.parse(readFileSync(path.join(work,'revision-v7/roughcut-v6.props.json'))).manifest;
assert.equal(m.editVersion,'v8');assert.deepEqual(m.cameras,old.cameras);assert.deepEqual(m.obs,old.obs);
const timing=evaluate(read('roughcut-timing.ts')),rows=timing.roughTimeline(m),chapters=timing.roughChapters(m),get=id=>rows.find(s=>s.id===id);
assert.equal(rows.length,50);assert.equal(chapters.length,6);assert.ok(get('r-higgsfield').from<get('s004').from);
assert.ok(get('r-teaser').duration>=117);assert.equal(get('r-teaser').end,1996.37);assert.equal(get('s007').start,242);assert.equal(get('s016').start,800.46);assert.equal(get('s019').start,987);assert.equal(get('s045').end,2459.03);
for(const r of rows){assert.ok(r.duration>0);assert.ok(r.start>=0&&r.end<=m.obs.duration);if(r.cameraSource){assert.ok(r.cameraStart>=0);const c=m.cameras.find(c=>c.source===r.cameraSource);assert.ok(r.cameraStart+r.duration/m.fps<c.duration+.04);}}
for(const id of ['s016','s017'])assert.ok(get(id).screenRedaction);
const assembly=read('RoughCut.tsx'),polish=read('YouTubeV8.tsx'),scenes=read('ScenesV8.tsx');
assert.match(assembly,/data-audio-role="obs-narration" src=\{staticFile\(m.obs.source\)\}/);
for(const code of [assembly,polish,read('YouTubeV8Primitives.tsx')])for(const tag of code.match(/<OffthreadVideo[\s\S]*?\/>/g)||[])assert.match(tag,/\bmuted\b/);
assert.match(assembly,/data-privacy-mask/);assert.match(assembly,/Four-frame J-cut/);
assert.doesNotMatch(assembly+polish+scenes,/Date\.now|Math\.random|setTimeout|requestAnimationFrame/);
const easing=evaluate(read('glass-motion.ts'));
const focus=evaluate(read('typing-focus.ts').replace(/^import .*\n/,''),easing);
for(const id of ['s020','s021','s023','s024','s025','s027','s030','s031'])for(let t=0;t<get(id).duration/m.fps;t+=1/30){
 const q=focus.typingFocus(id,t),tr=focus.screenTransform(q.zoom),b=focus.inputBounds,k=1760/1920;
 for(const [x,y] of [[b.left,b.top],[b.right,b.bottom]]){const px=x*k*tr.zoom+tr.tx,py=(y-focus.sourceCrop.top)*k*tr.zoom+tr.ty;assert.ok(px>=1.99&&px<=1760-1.99,id+' input x '+px);assert.ok(py>=1.99&&py<=focus.screenViewport.h-1.99,id+' input y '+py);}
 assert.ok(tr.ty>=focus.screenViewport.h*(1-tr.zoom)-.001 && tr.ty<=.001,'crop must fill viewport');
}
const fullCode=polish.slice(polish.indexOf('export const fullScenes='),polish.indexOf('const Definition:'));
const full=evaluate(fullCode,{roughTimeline:timing.roughTimeline}),fulls=full.fullScenes(m);
assert.equal(fulls.length,10);for(let i=1;i<fulls.length;i++)assert.ok(fulls[i].from>=fulls[i-1].from+fulls[i-1].duration);
const cueCode=polish.slice(polish.indexOf('export const v8Cues:'),polish.indexOf('export const chapterTitles'));
const {v8Cues}=evaluate(cueCode);assert.ok(v8Cues.length>=30);
const evCode=polish.slice(polish.indexOf('export const soundEvents='),polish.indexOf('export const YouTubeSound:'));
const {soundEvents}=evaluate(evCode,{roughTimeline:timing.roughTimeline,roughChapters:timing.roughChapters,v8Cues,fullScenes:full.fullScenes});
const events=soundEvents(m);assert.ok(events.length>65);assert.ok(!events.some(e=>/chime|ding|glass/.test(e.name)));
for(const a of JSON.parse(readFileSync(path.join(work,'public/v4/asset-ledger.json'))))assert.equal(createHash('sha256').update(readFileSync(path.join(work,'public/v4',a.file))).digest('hex'),a.sha256);
assert.equal(createHash('sha256').update(readFileSync(path.join(work,'public/cube.mov'))).digest('hex'),'0e9263ca447bb7e652bba4d1fcce7fb54e047d8024ad236e5c25530b773973aa');
for(const file of readdirSync(src).filter(n=>/\.tsx?$/.test(n)))transformSync(read(file),{loader:file.endsWith('tsx')?'tsx':'ts'});
assert.match(read('cinematic-brand.ts'),/google-fonts\/Manrope/);
assert.doesNotMatch(polish,/Wait until you see this/);
assert.match(assembly,/blur\(8px\)/);
assert.match(assembly,/data-teaser-playing-result/);
assert.match(read('YouTubeV8Primitives.tsx'),/BrandedBackground/);
assert.match(scenes,/w=\{881\}/);
assert.doesNotMatch(polish+scenes,/ProductionWorkshop|FilingIntake|DispatchStamp|ModelReel|Conveyor/);
const face=evaluate(read('face-motion.ts').replace(/^import .*\n/,''),{clamp01:easing.clamp01});
const crew=evaluate(read('crew-motion.ts').replace(/^import .*\n/gm,''),{...easing,...face});
for(const role of ['courier','operator','archivist'])for(let t=0;t<35;t+=1/30){const p=crew.crewPose(t,role,.35,80,1,'work');for(const n of Object.values(p.pose))assert.ok(Number.isFinite(n));assert.ok(p.pose.sy>.75&&p.pose.sy<1.2);}
assert.doesNotMatch(polish,/OriginalClaude|Companion|cgi-review/);
assert.doesNotMatch(polish,/Fine detail|s028|kind:'later'/);
assert.equal(v8Cues.filter(c=>c.kind==='lens').length,1);
assert.ok(v8Cues.some(c=>c.kind==='protip'));
assert.equal(get('s019').end,988+17/60);assert.equal(get('s026').start,1286.72);
assert.equal(get('r-no-code').end,977+16/30);
assert.match(read('YouTubeV8Primitives.tsx'),/leftOpen:aperture,rightOpen:aperture/);
for(const code of [polish,scenes,read('SupportingScenesV8.tsx')])for(const [,value] of code.matchAll(/lift=\{([\d.]+)\}/g))assert.ok(Number(value)>=0&&Number(value)<=1,'normalized actor lift pose');
assert.match(read('CameraPlate.tsx'),/data-person-aware-camera/);
assert.doesNotMatch(read('CameraPlate.tsx'),/maskImage|filter:/);
assert.match(scenes,/ballistic throw\/catch/);
const baseline=JSON.parse(readFileSync(path.join(project,'roughcut-v7-baseline.props.json'))).manifest;
assert.deepEqual(m.segments,baseline.segments,'Visual revision must preserve every narration edit');
assert.deepEqual(m.cameraPlate,baseline.cameraPlate);
assert.equal(new Set(fulls.map(s=>s.kind)).size,fulls.length,'No repeated full-scene kind');
const support=read('SupportingScenesV8.tsx');
assert.doesNotMatch(support,/<Film|claude-result|<Loop/,'No unrelated result clips in overlays');
assert.match(read('YouTubeV8Primitives.tsx'),/outfit=\{role as Outfit\}/);
assert.match(read('YouTubeV8Primitives.tsx'),/white-optical-glass/);
assert.match(polish,/cropX=lerp\(intro\?165:110,150,p\)/);
assert.match(polish,/avoidRaisedCamera=\{c.id==='s025'\|\|c.id==='s027'\}/);
assert.match(polish,/x=\{avoidRaisedCamera\?650:1260\}/);
assert.ok(650+540+95+20<1380,'Shifted brand card plus entrance/rotation allowance stays left of raised facecam');
const motifs=Object.values(evaluate(support.slice(support.indexOf('export const supportMotifs:'),support.indexOf('export const Support:'))).supportMotifs);
assert.equal(new Set(motifs).size,motifs.length,'Support mini-scene signatures must be unique');
const plateRows=JSON.parse(readFileSync(path.join(project,'person-plate-v7-segments.json')));
for(const r of rows){
 const p=r.id==='r-no-code'?{start:972.2,from:0,duration:160}:plateRows.find(p=>p.id===r.id),shift=Math.round(r.start*m.fps)-Math.round(p.start*m.fps);
 assert.equal(r.cameraPlateStart,p.from+shift);assert.ok(shift>=0&&shift+r.duration<=p.duration,'plate source coverage '+r.id);
 assert.equal(r.cameraPlateSource,r.id==='r-no-code'?'v7/no-code-complete.mp4':'v7/presenter-background.mp4');
}
for(const [source,hash] of Object.entries(m.cameraPlate.sourceHashes))assert.equal(createHash('sha256').update(readFileSync(path.join(work,'public',source))).digest('hex'),hash);
assert.equal(rows.at(-1).from+rows.at(-1).duration,14190);
console.log(JSON.stringify({passed:true,segments:rows.length,chapters:chapters.length,frames:rows.at(-1).from+rows.at(-1).duration,fullScenes:fulls.length,supportCues:v8Cues.length,soundEvents:events.length,typingBounds:'All focused frames safe',originalSync:true,cgiRemoved:true,sonyMuted:true},null,2));
