import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),video=path.join(repo,'video');
const project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement'),work=path.join(base,'work/higgsfield-replacement');
const require=createRequire(path.join(video,'package.json')),{transformSync}=require('esbuild');
const m=JSON.parse(readFileSync(path.join(project,'roughcut.props.json'))).manifest;
const v2=JSON.parse(readFileSync(path.join(work,'revision-v3/roughcut-v2.props.json'))).manifest;
assert.equal(m.editVersion,'v3');assert.deepEqual(m.cameras,v2.cameras);assert.deepEqual(m.obs,v2.obs);
const timing=readFileSync(path.join(video,'src/youtube/roughcut-timing.ts'),'utf8');
const box={module:{exports:{}}};runInNewContext(transformSync(timing,{loader:'ts',format:'cjs'}).code,box);
const rows=box.module.exports.roughTimeline(m),chapters=box.module.exports.roughChapters(m),get=id=>rows.find(s=>s.id===id);
assert.equal(rows.length,51);assert.equal(chapters.length,6);assert.ok(get('r-higgsfield').from<450);assert.ok(get('r-higgsfield').from<get('s004').from);
assert.ok(!get('s022'));assert.equal(get('s029').end,get('s030').start);
for(const id of ['s016','s017','s028']){assert.ok(get(id).screenRedaction);assert.equal(get(id).layout,'screen-presenter');}
assert.equal(get('s018').layout,'screen-presenter');
const assembly=readFileSync(path.join(video,'src/youtube/RoughCut.tsx'),'utf8'),polish=readFileSync(path.join(video,'src/youtube/YouTubePolish.tsx'),'utf8');
assert.match(assembly,/data-audio-role="obs-narration" src=\{staticFile\(m.obs.source\)\}/);
for(const tag of assembly.match(/<OffthreadVideo[\s\S]*?\/>/g))assert.match(tag,/\bmuted\b/);
assert.match(assembly,/data-privacy-mask/);assert.match(assembly,/Four-frame J-cut/);
assert.match(polish,/data-audio-role="design-sfx"/);assert.match(polish,/data-audio-role="music"/);
assert.doesNotMatch(assembly+polish,/Date\.now|Math\.random|setTimeout|requestAnimationFrame/);
const expression=polish.match(/export const openingScale=.*?;/)[0].replace('export ','');
const easeOut=(t,s,d)=>1-Math.pow(1-Math.max(0,Math.min(1,(t-s)/d)),4);
const scale=runInNewContext(transformSync(expression,{loader:'ts'}).code+';openingScale',{Math,easeOut});
assert.equal(scale(0),1);assert.ok(Math.abs(scale(4.5)-1.065)<1e-6);
assert.equal(createHash('sha256').update(readFileSync(path.join(work,'public/cube.mov'))).digest('hex'),'0e9263ca447bb7e652bba4d1fcce7fb54e047d8024ad236e5c25530b773973aa');
const assets=JSON.parse(readFileSync(path.join(work,'public/v3/asset-ledger.json')));
for(const a of assets)assert.equal(createHash('sha256').update(readFileSync(path.join(work,'public/v3',a.name))).digest('hex'),a.sha256);
console.log('PASS: 51 phrase-level selects, original sync, OBS sole narration, camera muted, private panels masked, 6 chapters, deterministic graphics, 6.5% decelerating zoom, original CGI + logo/SFX/music hashes.');
console.log('Duration:',(rows.at(-1).from+rows.at(-1).duration)/m.fps);
