import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement'),src=path.join(repo,'video/src/youtube');
const read=n=>readFileSync(path.join(src,n),'utf8'),old=p=>execFileSync('git',['show','016dcbe:'+p],{cwd:repo,encoding:'utf8'});
const require=createRequire(path.join(repo,'video/package.json')),{transformSync}=require('esbuild');
for(const f of readdirSync(src).filter(f=>/\.tsx?$/.test(f)))transformSync(read(f),{loader:f.endsWith('tsx')?'tsx':'ts'});
const props=JSON.parse(readFileSync(path.join(project,'roughcut.props.json'))),prior=JSON.parse(old('youtube-video-editing-system/projects/higgsfield-replacement/roughcut.props.json'));
const amended=structuredClone(props);const changed=amended.manifest.segments.find(s=>s.id==='s030'),original=prior.manifest.segments.find(s=>s.id==='s030');
assert.ok(Math.abs(changed.end-(1576.63-5/30))<1e-9);changed.end=original.end;changed.reason=original.reason;assert.deepEqual(amended,prior,'Only five nonverbal tail frames may leave the EDL; camera maps and sync unchanged');
for(const f of ['roughcut-timing.ts','glass-motion.ts','typing-focus.ts','Claude.tsx','CameraPlate.tsx','ScenesV21.tsx','AtmosphereV22.tsx'])assert.equal(read(f),old('video/src/youtube/'+f));
const rough=read('RoughCut.tsx');assert.equal(rough.slice(rough.indexOf('export const RoughCut:')),old('video/src/youtube/RoughCut.tsx').split('export const RoughCut:')[1]?'export const RoughCut:'+old('video/src/youtube/RoughCut.tsx').split('export const RoughCut:')[1]:'');
assert.match(rough,/data-audio-role="obs-narration" src=\{staticFile\(m.obs.source\)\}/);assert.match(rough,/data-privacy-mask/);assert.match(rough,/left:0,top:0,right:0,bottom:0,background:'#F4F2ED'/);assert.match(rough,/inset=\{x:1288,y:612.8,w:552,h:391.2\}/);assert.match(rough,/s.id==='s030'&&t>=30\?0/);
const box={module:{exports:{}}};runInNewContext(transformSync(read('roughcut-timing.ts'),{loader:'ts',format:'cjs'}).code,box);const rows=box.module.exports.roughTimeline(props.manifest),chapters=box.module.exports.roughChapters(props.manifest);assert.equal(rows.at(-1).from+rows.at(-1).duration,13708);assert.equal(chapters.length,6);assert.deepEqual(JSON.parse(JSON.stringify(chapters)),JSON.parse(readFileSync(path.join(project,'chapters.json'))));
const host=read('YouTubeV9.tsx');assert.match(host,/const CredentialSequence=CredentialV23/);assert.match(host,/c.kind==='keys'\?find\('s017'\).from\+3\*fps-r.from/);assert.match(host,/comparison\?432:480/);assert.match(host,/label="Reaction in"/);assert.match(host,/find\('r-veo-playthrough'\).from/);assert.match(host,/\.86\*easeInOut\(f\/fps,4.35,.45\)/);
const scene=read('ScenesV23.tsx');assert.match(scene,/length:240/);assert.match(scene,/Real API key hidden for privacy/);assert.match(scene,/13.05/);assert.match(scene,/14.25/);assert.doesNotMatch(scene,/Math.random|Date.now|setTimeout|sk-[A-Za-z0-9]{15}/);
assert.deepEqual(JSON.parse(readFileSync(path.join(project,'v23-timeline.json'))),JSON.parse(JSON.stringify(rows)));
const chapterText=readFileSync(path.join(project,'chapters.ffmetadata'),'utf8');
assert.equal(chapterText,';FFMETADATA1\n'+chapters.map((c,i)=>`[CHAPTER]\nTIMEBASE=1/30\nSTART=${c.frame}\nEND=${chapters[i+1]?.frame??13708}\ntitle=${c.title}\n`).join(''));
execFileSync(process.execPath,[path.join(project,'tools/prepare-v23-media.mjs'),'--check-only'],{stdio:'inherit'});
assert.match(read('ScenesV22.tsx'),/<ModelLineupV23/);assert.match(read('ScenesV20.tsx'),/<HundredsV23/);assert.match(read('ScenesV9.tsx'),/FeatureVault=VaultV20/);assert.match(read('ScenesV22.tsx'),/width:345,textAlign:'center'/);
for(const row of JSON.parse(readFileSync(path.join(project,'provenance/media-v21.json'))))for(const [name,sha] of [[row.source,row.sourceSHA256],[row.target,row.targetSHA256]])assert.equal(createHash('sha256').update(readFileSync(path.join(base,'work/higgsfield-replacement/public',name))).digest('hex'),sha);
console.log('PASS V23: TS/TSX parsing, exact five-frame EDL delta, unchanged OBS narration implementation/camera maps/rig/intro grades, credential cover and extended walkthrough, larger anchored insets, model/hundreds actions and reaction/playback audio wiring. Fresh full render required.');
