import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement');
const read=n=>readFileSync(path.join(repo,'video/src/youtube',n),'utf8');
execFileSync(process.execPath,[path.join(project,'tools/test-v13.mjs')],{stdio:'inherit'});
execFileSync(process.execPath,[path.join(project,'tools/prepare-v21-cache.mjs'),'--check-only'],{stdio:'ignore'});
const s=read('ScenesV21.tsx'),host=read('YouTubeV9.tsx');
assert.match(s,/globalSeconds<31\?30:0/);
const titles=s.match(/roadmapTitlesV21=\[([^\]]+)\]/)[1].match(/'([^']+)'/g).map(x=>x.slice(1,-1));
for(const title of titles)assert.ok(host.includes("'"+title+"'"),'Roadmap matches chapter: '+title);
assert.match(s,/y=\{102\}/);assert.match(s,/fontSize:45/);assert.match(s,/fontSize:43/);
assert.match(host,/roadmap-ding',\.24,1\.2/);
assert.match(s,/land=1\.58/);assert.match(s,/throwP=e\(u,3\.0,\.84\)/);assert.match(s,/deliver=e\(u,5\.44,1\.0\)/);assert.match(s,/save=e\(u,6\.55,\.68\)/);
assert.doesNotMatch(s,/Math.random|Date.now|setTimeout|<Tree|<Cabin|<Forest/);
assert.match(read('ScenesV20.tsx'),/higgsfield-scroll-v20.png/);
const ledger=JSON.parse(readFileSync(path.join(project,'provenance/media-v21.json')));
assert.equal(ledger.length,2);assert.equal(ledger[0].correction,ledger[1].correction);
for(const row of ledger)for(const [name,sha] of [[row.source,row.sourceSHA256],[row.target,row.targetSHA256]])assert.equal(createHash('sha256').update(readFileSync(path.join(base,'work/higgsfield-replacement/public',name))).digest('hex'),sha);
assert.match(read('StoryScenesV10.tsx'),/opening\?\(i\?'v9\/intro-claude-v21.mp4':'v9\/intro-higgsfield-v21.mp4'\):\(i\?'v4\/claude-result.mp4':'v9\/higgsfield-comparison.mp4'\)/);
console.log('PASS V21: intro-only crop, chapter-matched top labels, quiet dings, finite scene action clocks, original media unchanged, equal opening derivatives and exact V20 source-scope reversal.');
