import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement');
const baseline='4d40d78',read=n=>readFileSync(path.join(repo,'video/src/youtube',n),'utf8');
const old=p=>execFileSync('git',['show',baseline+':'+p],{cwd:repo,encoding:'utf8'});
execFileSync(process.execPath,[path.join(project,'tools/test-v13.mjs')],{stdio:'inherit'});
for(const name of ['RoughCut.tsx','roughcut-timing.ts','glass-motion.ts','typing-focus.ts','Claude.tsx'])assert.equal(read(name),old('video/src/youtube/'+name),'Protected narration/sync/rig: '+name);
assert.equal(readFileSync(path.join(project,'roughcut.props.json'),'utf8'),old('youtube-video-editing-system/projects/higgsfield-replacement/roughcut.props.json'));
const host=read('YouTubeV9.tsx'),prior=old('video/src/youtube/YouTubeV9.tsx');
assert.equal(host.split('export const soundEvents=')[0],prior.split('export const soundEvents=')[0],'All scene/cue clocks and presenter placement preserved');
assert.equal(host.slice(host.indexOf('export const YouTubeSound:')),prior.slice(prior.indexOf('export const YouTubeSound:')),'Music/narration mixing levels preserved');
assert.match(host,/add\(b\+7\.17,'latch',\.065\)/);assert.match(host,/beat\(\.63,d,'latch',\.065\)/);assert.match(host,/beat\(\.85,d,'paper',\.055\)/);
const scene=read('ScenesV22.tsx');
assert.match(scene,/data-editorial-octopus/);assert.match(scene,/length:8/);assert.match(scene,/higgsfield.jpg/);
assert.match(scene,/mechanical-stopwatch/);assert.match(scene,/strokeDashoffset=\{p\}/);assert.match(scene,/Math.max\(1,3-Math.floor\(u\)\)/);
assert.match(scene,/actorX\+134/);assert.match(scene,/Saved on your computer/);assert.match(scene,/Downloads/);
assert.match(scene,/role="archivist"/);assert.match(scene,/role="courier"/);assert.match(scene,/role="operator"/);
assert.match(scene,/whiteSpace:'nowrap'/);assert.doesNotMatch(scene,/Ready for your first prompt|Math.random|Date.now|setTimeout/);
assert.match(read('ScenesV9.tsx'),/ProductionV9=ProductionV22/);assert.match(read('ScenesV9.tsx'),/GuideV9=GuideV22/);assert.match(read('ScenesV9.tsx'),/OutroV9=OutroV22/);
assert.match(read('ScenesV9.tsx'),/CostV22 as CostV20/);assert.match(scene,/Two connected cost mechanisms/);assert.match(read('YouTubeV8Primitives.tsx'),/data-character-separation="ink-rim"/);
assert.match(read('ScenesV9.tsx'),/FeatureVault=VaultV20/);
assert.match(read('ScenesV21.tsx'),/<OctopusV22/);assert.match(read('ScenesV21.tsx'),/globalSeconds<31\?30:0/);
assert.match(read('SupportingScenesV9.tsx'),/<SavedOverlayV22/);assert.match(read('SupportingScenesV9.tsx'),/<MixOverlayV22/);
assert.match(read('YouTubeV6Primitives.tsx'),/AtmosphereV22 as BrandedBackground/);assert.match(read('AtmosphereV22.tsx'),/radial-gradient/);
assert.match(read('StoryScenesV10.tsx'),/t>=1.6&&t<4.6&&<StopwatchV22/);
const ledger=JSON.parse(readFileSync(path.join(project,'provenance/media-v21.json')));
for(const row of ledger)for(const [name,sha] of [[row.source,row.sourceSHA256],[row.target,row.targetSHA256]])assert.equal(createHash('sha256').update(readFileSync(path.join(base,'work/higgsfield-replacement/public',name))).digest('hex'),sha,'Original/equal intro-grade media: '+name);
console.log('PASS V22: V21 EDL, narration, camera clocks, music mix, originals/intro grades preserved; warm environment, octopus, stopwatch, action-led role scenes and retimed quiet contact SFX wired. All pictures require fresh rendering.');
