import './test-v13.mjs';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
const base=process.cwd(),repo=path.join(base,'work/repos/claude-reels-workflow'),project=path.join(repo,'youtube-video-editing-system/projects/higgsfield-replacement');
const proof=JSON.parse(execFileSync(process.execPath,[path.join(project,'tools/prepare-v15-cache.mjs'),'--check-only'],{encoding:'utf8',maxBuffer:5e6}));
assert.deepEqual(proof.affected,[{from:220,to:1757}]);
const src=readFileSync(path.join(repo,'video/src/youtube/ScenesV15.tsx'),'utf8');
for(const component of ['CostV15','ProductionV15','RoadmapV15','GuideV15','WrapperV15'])assert.ok(src.includes('export const '+component));
assert.doesNotMatch(src,/Math\.random|Date\.now|setTimeout|<Audio|1,?000\s*[×x](?![a-z])/);
for(const tag of src.match(/<OffthreadVideo[\s\S]*?\/>/g)||[])assert.match(tag,/\bmuted\b/);
assert.match(src,/plan includes credits/);assert.match(src,/model costs vary/);assert.match(src,/matched per-video cost/);
assert.match(src,/not an official mascot/);assert.match(src,/Actual demo · condensed/);
assert.match(src,/start=\{1008\}/);assert.match(src,/start=\{1054\}/);assert.match(src,/start=\{1530\}/);
assert.match(src,/FREE setup/);assert.match(src,/Description ↓/);
assert.ok(990+40+165*1.2<1280,'Skill graphic clears price at maximum travel');
assert.ok(691+40<748,'Cost label clears the fixed presenter box');
const story=readFileSync(path.join(repo,'video/src/youtube/StoryScenesV10.tsx'),'utf8');
assert.match(story,/width:opening\?916:938,height:opening\?1016:742/);
console.log('PASS V15: visual-first intro, separate scene actions, muted real-result playback, original blind comparison, price units, editorial mascot, and unchanged later picture/narration scope.');
