import React from 'react';
import {AbsoluteFill, Audio, Freeze, Img, OffthreadVideo, interpolate, Easing, staticFile, useCurrentFrame, spring} from 'remotion';
import {Bg, HookHeader, ProgressBar, KaraokeCaption, Mascot} from './SlopKit';
import {inter, fraunces} from './fonts';
import words from './data/words_lm146.json';
import edl from './data/edl_lm146.json';
import capture from '../public/lm146/capture-manifest.json';
const FPS=30, C='#D97757', V='#6544EB', NAVY='#111C2F', GREEN='#398F68';
const ease=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)});
const mix=(a:number,b:number,p:number)=>a+(b-a)*p;
const step=(name:string)=>edl.find(e=>e.name===name)!;
const at=(name:string)=>Math.round(step(name).start*30);
const ends=(name:string)=>Math.round(step(name).end*30);
const file=(s:string)=>staticFile('lm146/'+s);
type Rect=[number,number,number];
// All imagery below is captured from the real app or the official website.
// Camera crops are editorial; no labels, responses, warnings, or UI values are altered.
const Footage:React.FC<{name:string; local:number; cam:Rect; to?:Rect; move?:[number,number]; offset?:number; rate?:number; still?:boolean;height?:number}>=({name,local,cam,to,move=[0,35],offset=0,rate=1,still=false,height=650})=>{
 const p=ease(local,move[0],move[1]);const r=cam.map((v,i)=>mix(v,(to||cam)[i],p)) as Rect;const s=964/r[2];
 const max=Math.max(0,Math.floor(((capture as any)[name]?.seconds||1)*30)-3);
 const sourceFrame=Math.min(max,Math.max(0,Math.floor(local*rate+offset*30)));
 const style:React.CSSProperties={position:'absolute',left:-r[0]*s,top:-r[1]*s,width:(name.startsWith('website')||name.startsWith('official-model')?1280:1200)*s,maxWidth:'none'};
 return <div style={{position:'absolute',left:24,top:94,width:964,height,overflow:'hidden',borderRadius:22,background:'#fff',boxShadow:'0 16px 32px #0004'}}>{still?<Img src={file(name+'-last.png')} style={style}/>:<Freeze frame={sourceFrame}><OffthreadVideo src={file(name+'.mp4')} muted style={style}/></Freeze>}</div>;
};
const Frame:React.FC<{title:string;number:string;children:React.ReactNode;tag?:string}>=({title,number,children,tag})=><div style={{position:'absolute',left:34,top:500,width:1012,height:790,borderRadius:38,background:'linear-gradient(145deg,#17253D,#0B1423)',boxShadow:'0 32px 65px #17253d55, inset 0 2px 0 #ffffff33',border:'2px solid #25364F',overflow:'hidden'}}><div style={{position:'absolute',left:30,top:29,display:'flex',alignItems:'center',gap:17,color:'white',fontFamily:inter.fontFamily,fontWeight:700,fontSize:28}}><span style={{background:V,borderRadius:12,padding:'6px 12px',fontSize:22}}>{number}</span>{title}</div><div style={{position:'absolute',right:34,top:38,fontFamily:inter.fontFamily,fontSize:19,color:'#BED0E8',letterSpacing:1.3}}>{tag||'LM STUDIO'}</div>{children}<div style={{position:'absolute',left:34,bottom:15,fontFamily:inter.fontFamily,fontSize:15,letterSpacing:1.3,color:'#8DA0BC'}}>REAL SCREEN CAPTURE</div></div>;
const ContactRing:React.FC<{f:number;x:number;y:number;color?:string}>=({f,x,y,color=C})=>{const p=ease(f,0,15);return f>=0&&f<18?<div style={{position:'absolute',left:x-34,top:y-34,width:68,height:68,borderRadius:'50%',border:`5px solid ${color}`,opacity:1-p,transform:`scale(${.4+p*1.3})`}}/>:null;};
const Hook:React.FC=()=>{
 const f=useCurrentFrame();const travel=ease(f,12,48), impact=Math.exp(-Math.max(0,f-48)/9)*Math.sin(Math.max(0,f-48)*.65);const zoom=f<36?1+.045*ease(f,0,36):1.13+.035*ease(f,36,88);
 const modelX=mix(392,587,travel), modelY=mix(120,449,travel), modelSize=mix(310,138,travel);
 const bodyX=mix(71,245,ease(f,5,40));const crouch=ease(f,3,10)*(1-ease(f,12,24));const reaction=ease(f,50,60);
 return <div style={{position:'absolute',left:34,top:500,width:1012,height:790,borderRadius:38,overflow:'hidden',background:'radial-gradient(ellipse at 65% 33%,#FAF7FF 0%,#EBE9F7 40%,#DDE7E7 100%)',border:'2px solid #F9F7F0',boxShadow:'0 30px 65px #17253d44'}}>
  <div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(#8274aa12 1px,transparent 1px),linear-gradient(90deg,#8274aa12 1px,transparent 1px)',backgroundSize:'44px 44px',maskImage:'linear-gradient(transparent,#000)'}}/>
  <div style={{position:'absolute',left:38,top:30,fontFamily:inter.fontFamily,fontWeight:800,fontSize:24,color:V,letterSpacing:2}}>QWEN3.8-27B</div>
  <div style={{position:'absolute',inset:0,transform:`scale(${zoom})`,transformOrigin:'55% 57%'}}>
   <div style={{position:'absolute',left:347,top:346,width:534,height:286,border:'15px solid #273044',borderRadius:27,background:'#fff',boxShadow:'0 26px 44px #29354a44',transform:`translateY(${impact*5}px)`}}>
    <div style={{position:'absolute',top:17,left:22,fontFamily:inter.fontFamily,fontSize:20,fontWeight:700,color:'#79718F'}}>YOUR COMPUTER</div>
    <div style={{position:'absolute',left:220,top:89,width:160,height:118,borderRadius:20,border:`3px ${reaction>.2?'solid':'dashed'} ${reaction>.2?GREEN:'#BCB5D4'}`,background:reaction>.2?'#E5F3EC':'#F0ECF9'}}/>
    {reaction>.05&&<div style={{position:'absolute',left:37,right:37,bottom:18,display:'flex',justifyContent:'center',gap:12,color:GREEN,fontFamily:inter.fontFamily,fontSize:23,fontWeight:800,opacity:reaction}}><span>✓</span>LOCAL AI</div>}
   </div>
   <div style={{position:'absolute',left:310,top:630,width:610,height:34,borderRadius:'4px 4px 45px 45px',background:'linear-gradient(#9AA6B6,#697990)',boxShadow:'0 27px 24px #35435333'}}/>
   <div style={{position:'absolute',left:475,top:480,width:91,height:56,borderRadius:12,background:reaction>.2?GREEN:V,boxShadow:'0 6px 0 #3A286D',transform:`translateY(${ease(f,36,40)*(1-ease(f,43,50))*5}px)`,display:'flex',alignItems:'center',justifyContent:'center',color:'white',fontFamily:inter.fontFamily,fontSize:18,fontWeight:850}}>{reaction>.2?'✓':'LOAD'}</div>
   <div style={{position:'absolute',left:505,top:630,width:206,height:12,background:'#58657B',borderRadius:'0 0 20px 20px'}}/>
   <div style={{position:'absolute',left:bodyX+16,top:643,width:240,height:32,borderRadius:'50%',background:'#4D405F24',filter:'blur(8px)',transform:`scaleX(${1+crouch*.12})`}}/>
   <div style={{position:'absolute',left:bodyX,top:351+22*crouch-12*reaction,transform:`rotate(${mix(-8,5,ease(f,12,40))*(1-reaction)}deg) scaleY(${1-.12*crouch})`,transformOrigin:'50% 95%'}}><Mascot lf={f+24} size={315} nodAmp={0} gaze={7*(1-reaction)} stern={crouch*.65} shock={f<50?.08:.55*(1-ease(f,58,72))} cheer={reaction*.88}/></div>
   <div style={{position:'absolute',left:modelX,top:modelY,width:modelSize,height:modelSize*.78,borderRadius:28,background:'linear-gradient(145deg,#8B73FF,#5636D6)',boxShadow:`${10*(1-travel)}px ${16*(1-travel)+5}px 0 #3D278D, 0 25px 38px #6746d455`,border:'3px solid #C1B0FF',transform:`rotate(${mix(-8,0,travel)+impact*2}deg)`,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',color:'#fff'}}><span style={{fontFamily:inter.fontFamily,fontSize:mix(93,44,travel),fontWeight:900,lineHeight:1}}>27B</span><span style={{fontFamily:inter.fontFamily,fontSize:mix(23,12,travel),letterSpacing:2,fontWeight:700,marginTop:10}}>PARAMETERS</span></div>
   <ContactRing f={f-48} x={658} y={505} color={V}/>
  </div>
  <div style={{position:'absolute',bottom:35,left:0,right:0,textAlign:'center',fontFamily:inter.fontFamily,fontWeight:750,fontSize:30,color:'#403851',opacity:ease(f,55,67)}}>Find the version your machine can run.</div>
 </div>;
};
const QuantScale:React.FC<{f:number}>=({f})=>{const p=ease(f,7,94);return <div style={{position:'absolute',left:252,top:1330,right:60}}><div style={{display:'flex',justifyContent:'space-between',fontFamily:inter.fontFamily,fontWeight:800,fontSize:29,color:'#383041'}}><span>SMALLER FILE</span><span>MORE PRECISION</span></div><div style={{height:15,background:'#D4CFE2',borderRadius:20,marginTop:17,position:'relative'}}><div style={{height:15,width:`${25+p*75}%`,background:`linear-gradient(90deg,${V},${C})`,borderRadius:20}}/><div style={{position:'absolute',left:`${10+p*82}%`,top:-8,width:31,height:31,borderRadius:'50%',background:C,border:'4px solid white',boxShadow:'0 4px 10px #0002'}}/></div><div style={{display:'flex',justifyContent:'space-between',fontFamily:inter.fontFamily,fontSize:23,color:'#716978',marginTop:10}}><span>4-bit</span><span>8-bit</span></div></div>;};
const SideNote:React.FC<{text:string;detail?:string;f:number;success?:boolean;quant?:boolean}>=({text,detail,f,success,quant})=>{
 const anticipate=ease(f,0,8)*(1-ease(f,9,17));const settle=ease(f,17,28);
 return <><div style={{position:'absolute',left:51,top:1291,transform:`translateY(${-8*settle+7*anticipate}px) rotate(${(-5*anticipate+3*settle)}deg)`}}><Mascot lf={f+26} size={170} nodAmp={0} gaze={5} stern={anticipate*.55} shock={success?.45*(1-ease(f,15,26)):.04} cheer={success?settle*.7:.2}/></div>{quant?<QuantScale f={f}/>:<div style={{position:'absolute',left:248,right:65,top:1321,fontFamily:inter.fontFamily}}><div style={{fontWeight:850,fontSize:33,color:success?GREEN:'#332D3C',lineHeight:1.17}}>{text}</div>{detail&&<div style={{marginTop:10,fontWeight:500,fontSize:23,color:'#7A7280',lineHeight:1.25}}>{detail}</div>}</div>}</>;
};
const CTA:React.FC=()=>{const f=useCurrentFrame()-at('cta');const p=spring({fps:30,frame:f,config:{damping:17,stiffness:180}});const press=ease(f,6,13)*(1-ease(f,14,20));return <div style={{position:'absolute',left:34,top:500,width:1012,height:790,borderRadius:38,overflow:'hidden',background:'radial-gradient(ellipse at 55% 36%,#FFFFFF,#E8E4F2)',boxShadow:'0 30px 65px #17253d44'}}><div style={{position:'absolute',left:100,top:80,fontFamily:inter.fontFamily,fontWeight:800,fontSize:45,color:'#302A3C'}}>Your local AI setup.</div><div style={{position:'absolute',left:120,top:210,width:770,height:212,borderRadius:32,background:'#FFF',border:'3px solid #D7CFE4',boxShadow:'0 22px 45px #49356925',transform:`scale(${.94+.06*p})`,display:'flex',alignItems:'center',justifyContent:'center',gap:28}}><span style={{fontFamily:inter.fontFamily,fontSize:49,fontWeight:700,color:'#312A3E'}}>Comment</span><div style={{padding:'16px 32px',background:V,color:'white',borderRadius:23,fontFamily:inter.fontFamily,fontSize:84,fontWeight:900,transform:`translateY(${press*8}px) scale(${1-press*.04})`,boxShadow:`0 ${9-press*7}px 0 #382184`}}>LM</div></div><div style={{position:'absolute',left:630,top:425,transform:`translateY(${press*10}px)`}}><Mascot lf={f+26} size={244} nodAmp={0} gaze={-6} cheer={ease(f,18,29)} shock={.4*(1-ease(f,14,23))}/></div><div style={{position:'absolute',left:115,top:510,fontFamily:inter.fontFamily,fontSize:31,fontWeight:650,lineHeight:1.65,color:'#635A73'}}><div>01 Install LM Studio</div><div>02 Pick a model that fits</div><div>03 Start a local chat</div></div><ContactRing f={f-14} x={665} y={330} color={V}/></div>;};
export const ClaudeLM146Reel:React.FC=()=>{
 const f=useCurrentFrame();let idx=edl.findIndex((e,i)=>f>=Math.round(e.start*30)&&(i===edl.length-1||f<Math.round(edl[i+1].start*30)));if(idx<0)idx=0;const scene=edl[idx].name;const lf=f-at(scene);
 let big='LOCAL AI, STEP BY STEP', hot='ON YOUR COMPUTER.';
 let title='',number='',name='',cam:Rect=[0,0,1200],to:Rect|undefined,local=lf,offset=0,rate=1,still=false,height=650,move:[number,number]=[0,35],tag='LM STUDIO';let note='',detail='',success=false,quant=false;
 if(scene==='hook'){big='27 BILLION PARAMETERS';hot='ON YOUR COMPUTER.';}
 if(scene==='download'){big='START WITH LM STUDIO';hot='A FREE LOCAL AI APP.';title='Download the app';number='01';name=lf<51?'website-detail':'website-os';local=lf<51?lf:lf-51;cam=[173,68,820];to=[176,77,690];note='lmstudio.ai/download';detail='Choose LM Studio for your operating system.';tag='OFFICIAL WEBSITE';}
 if(scene==='search'){big='FIND YOUR MODEL';hot='CHECK THE SOURCE.';title=lf<81?'Search Qwen3.8-27B':'Verify the original model';number='02';name=lf<81?'search38':'official-model38';local=lf<81?lf:lf-81;rate=lf<81?6:1;offset=lf<81?.4:0;cam=lf<81?[85,78,1025]:[0,69,775];to=lf<81?[91,82,530]:[4,75,745];note=lf<81?'Search: Qwen3.8-27B':'Original model: Qwen';detail=lf<81?'Choose a compatible GGUF download.':'GGUF files are community conversions.';tag=lf<81?'LM STUDIO':'HUGGING FACE';}
 if(scene==='quant'){big='4, 5, 6 OR 8 BIT?';hot='PICK YOUR QUANTIZATION.';title='Compare the download options';number='03';name='search38';still=true;cam=[102,170,390];height=155;const qtimes=[0,13,26,44];const ys=[170,386,314,242];let j=0;while(j<3&&lf>=qtimes[j+1])j++;const prev=Math.max(0,j-1);cam=[102,ys[j],390];note=['4-bit','5-bit','6-bit','8-bit'][j]+' quantization';detail='Same model family. Different file sizes.';}
 if(scene==='compression'||scene==='best'){big=scene==='compression'?'QUANTIZATION = COMPRESSION':'CHOOSE WHAT FITS';hot=scene==='compression'?'SIZE VS. PRECISION.':'KEEP MORE PRECISION.';title='Balance size and compression';number='03';name='quant38';still=true;cam=scene==='compression'?[520,324,580]:[520,356,575];to=scene==='compression'?[524,332,574]:[524,360,570];quant=scene==='compression';note='Use the least compressed option that fits.';detail='Leave room for the app and context, too.';}
 if(scene==='fit'){big='WILL IT RUN ON YOUR MAC?';hot='CHECK BEFORE DOWNLOADING.';title=lf<99?'Read the hardware estimate':'Pick a model that fits';number='04';name=lf<99?'fit38':'download-model';local=lf<99?lf:lf-99;cam=lf<99?[510,280,590]:[510,270,590];to=lf<99?[520,310,570]:[515,280,580];note=lf<99?'27B: “Likely too large” on this Mac':'1.7B demo: fits this Mac';detail=lf<99?'Your available memory determines the fit.':'Smaller community model used for the live chat.';success=lf>=99;}
 if(scene==='models'){big='OPEN YOUR DOWNLOADED MODEL';hot='GO TO MY MODELS.';title='Open My Models';number='05';name='my-models';height=350;cam=[0,28,1200];to=[41,34,1155];note='Live demo: Qwen3 • 1.7B uncensored';detail='The chat demo uses this smaller community variant.';}
 if(scene==='load'){big='ONE MODEL. A NEW CHAT.';hot='LOAD IT LOCALLY.';title=lf<70?'Open the model settings':'Use in New Chat';number='05';name=lf<95?'model-config':'use-new-chat';local=lf<95?lf:lf-95;offset=lf<95?0:3.48;move=[0,30];cam=lf<95?[330,35,870]:[327,38,530];to=lf<95?[843,35,350]:[335,38,510];note='Qwen3 • 1.7B uncensored';detail='Model settings → Use in New Chat';success=lf>100;}
 if(scene==='chat'){big='NOW CHAT WITH LOCAL AI';hot='THINK. WRITE. CODE.';title=lf<67?'Reasoning locally':'Code generated on this Mac';number='05';name=lf<67?'chat-response':'code-final';local=lf<67?lf:lf-67;cam=lf<67?[149,155,865]:[155,223,440];to=lf<67?[151,183,810]:[157,235,415];rate=lf<67?8:1;offset=lf<67?2:0;note='Live demo: Qwen3 • 1.7B uncensored';detail=lf<67?'Recording shown at 8× speed.':'Actual local output. No cloud inference.';success=true;tag=lf<67?'8× SPEED':'LOCAL RESPONSE';}
 if(scene==='cta'){big='WANT THE SETUP?';hot='COMMENT “LM”.';}
 return <AbsoluteFill style={{fontFamily:inter.fontFamily}}><Bg/><div style={{position:'absolute',top:116,left:55,right:55,display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:25,fontWeight:750,letterSpacing:3,color:'#7F746C'}}><span>LOCAL AI • PRACTICAL DEMO</span><span style={{fontSize:21,letterSpacing:1}}>QWEN × LM STUDIO</span></div><ProgressBar/><HookHeader big={big} hot={hot} f={100}/>{scene==='hook'?(lf<90?<Hook/>:<><Frame title="Meet Qwen3.8-27B" number="27B" tag="OFFICIAL MODEL"><Footage name="official-model38" local={lf-90} cam={[0,69,775]} to={[4,75,745]}/></Frame><SideNote text="27 billion language parameters" detail="Choose a version that fits your hardware." f={lf-90}/></>):scene==='cta'?<CTA/>:<><Frame title={title} number={number} tag={tag}><Footage name={name} local={local} cam={cam} to={to} offset={offset} rate={rate} still={still} height={height} move={move}/>{scene==='models'&&<div style={{position:'absolute',left:42,right:42,top:515,fontFamily:inter.fontFamily,color:'white'}}><div style={{color:'#ADBED8',fontSize:23,letterSpacing:2,marginBottom:25}}>THREE CLICKS TO A LOCAL CHAT</div><div style={{display:'flex',gap:18,alignItems:'center'}}>{['My Models','Settings','New Chat'].map((x,i)=><React.Fragment key={x}>{i>0&&<span style={{color:'#A697F2',fontSize:34}}>→</span>}<div style={{background:i===0?V:'#23344F',padding:'23px 18px',borderRadius:18,fontWeight:800,fontSize:29,opacity:.55+.45*ease(lf,i*13,i*13+12)}}>{x}</div></React.Fragment>)}</div></div>}{scene==='quant'&&<div style={{position:'absolute',top:464,left:44,right:44,fontFamily:inter.fontFamily}}><div style={{fontSize:22,color:'#AEBFD6',letterSpacing:2,marginBottom:26}}>CHOOSE A COMPRESSION LEVEL</div><div style={{display:'flex',gap:17}}>{[4,5,6,8].map((x,i)=>{const active=lf>=[0,13,26,44][i]&&(i===3||lf<[0,13,26,44][i+1]);return <div key={x} style={{flex:1,padding:'23px 0',borderRadius:24,textAlign:'center',background:active?V:'#24334B',transform:`translateY(${active?-7:0}px)`,boxShadow:active?'0 8px 0 #3E268D':'none',color:active?'#FFF':'#899AB5'}}><span style={{fontSize:66,fontWeight:900}}>{x}</span><div style={{fontSize:23,fontWeight:650}}>BIT</div></div>})}</div></div>}</Frame><SideNote text={note} detail={detail} f={lf} success={success} quant={quant}/></>}
 <KaraokeCaption words={words} top={1475}/><div style={{position:'absolute',left:60,right:60,top:1735,height:2,background:'#B9AC9936'}}/><div style={{position:'absolute',left:60,right:60,top:1764,fontSize:21,color:'#8D8176',letterSpacing:1.5,fontWeight:650,display:'flex',justifyContent:'space-between'}}><span>NO CLOUD REQUIRED FOR LOCAL CHAT</span><span>COMMENT LM</span></div><Audio src={file('master.wav')}/></AbsoluteFill>;
};
